//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogCueWriteMicroservices.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        
        public int Customer { get; set; }
        
        [JsonProperty("Adress")]
        public string Adress { get; set; }
        public int Type { get; set; }

        public Contact()
        {

        }
        public Contact(int customer,string adress, int type)
        {
            Customer = customer;
            Adress = adress;
            Type = type;
        }
        
    }
}
